#!/bin/sh

gpg --encrypt \
  --recipient alex.duzh@gmail.com \
  --recipient ejabberd@gmail.com \
  --recipient puzinok@gmail.com \
  --recipient alex.kalinoff@gmail.com \
  --recipient ahiskali1@gmail.com \
  --recipient svishniakov@gmail.com \
  envrc
